package dersCalisma2;

import java.io.IOException;

public class trycatchdene {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

/*		try {

			int a = 3 - 3;
			int b = 2 / a;
			System.out.println("" + b);

		}

		catch (Exception e1) {
			e1.getStackTrace();

		} catch (ArithmeticException e2)  {
			System.err.print("heeyy");
		}

		finally {
		}
*/
		
	public static void A()throws  MyException{
	int c=3-3;
	int x=c/5;
	}	
		
	}
	
}
//}*/
